-- 오프라인/온라인 판매 데이터 통합하기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131537
-- 작성자: 김하은
-- 작성일: 2026. 01. 19. 23:53:20

SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALE_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION ALL

SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALE_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALE_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;