-- 상품을 구매한 회원 비율 구하기
-- 프로그래머스 고급 (⭐⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131534
-- 작성자: 김하은
-- 작성일: 2026. 01. 19. 23:57:17

WITH USER_2021 AS (
    SELECT COUNT(*) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
PURCHASED AS (
    SELECT
        YEAR(S.SALES_DATE) AS YEAR,
        MONTH(S.SALES_DATE) AS MONTH,
        COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE S
    JOIN USER_INFO U
        ON S.USER_ID = U.USER_ID
    WHERE YEAR(U.JOINED) = 2021
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
)
SELECT
    P.YEAR,
    P.MONTH,
    P.PURCHASED_USERS,
    ROUND(P.PURCHASED_USERS / U.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM PURCHASED P
CROSS JOIN USER_2021 U
ORDER BY P.YEAR, P.MONTH;